<Project Sdk="Godot.NET.Sdk/4.7.2">

	<PropertyGroup>
		<AssemblyTitle>XTower</AssemblyTitle>
		<TargetFramework>net10.0</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<IsPackable>false</IsPackable>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<EnableDefaultAvaloniaItems>false</EnableDefaultAvaloniaItems>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ouse.Estragonia" />
		<PackageReference Include="Semi.Avalonia" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="UI/Assets/**" />
		<None Include="**\*.axaml" />
		<Compile Update="**\*.axaml.cs">
			<DependentUpon>%(Filename)</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
